### ISSUE TITLE
Bug/Cannot have playback start inside of a second detected take

### ISSUE THREAD

**Issue by Irmy** [patrickbrett/mlvet#241] opened 2022-08-31 03:09 UTC
You can have the payback start anywhere in the first detected take of a set, however cannot do the same for the second version of that take group. Even when the second take is selected, it wont playback from anywhere in that take, but rather starts from the beginning
https://user-images.githubusercontent.com/55219708/187583942-a6c67339-8909-4e48-8b04-16235ecd815b.mp4

**Comment by chloebrett** [comment] 2022-10-02 10:26
I think the issue is that the UI allows you to click/select a word in a non-selected take, but the playback will refuse to play that take. This will presumably be resolved by necessity in the "play a preview of the take you're about to select" feature, but let's keep an eye out. In my own testing I was able to start playback from any word in the entire transcription, as long as the word was not in a non-selected take - if it was, then selecting that take made the word playable.

**Closed as completed** 2022-10-12 23:41 UTC
Labels: bug, low priority
